apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: demo
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: tssc.jfrog.io/tssc-docker/bootstrap:d76aa82225e3435fa89d5d7067ace31d0d52632f@sha256:799bcbcf1eda037848078d38ee8687f4040b821009eefdcd9ae5ecd4c77b158a
          name: container-image
